baseURL = "https://hooskers.github.io"
title = "Wade Johnson"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"
logo = "/images/poop.png"

[params.info]
description = "Javascript Engineer"
title404 = "Nothing's here!"

[params.assets]
favicon = "/favicon.ico"
customCSS = ["css/custom.css"]
customJS = []
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = ""
startYear = ""
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true

[params.sidebar]
enable = true
sticky = true

[params.widgets]
homepage = []
sidebar = ["about"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
#codepen = "MunifTanjim"
email = "wadej93@gmail.com"
#facebook = "MunifTanjim"
github = "hooskers"
#gitlab = "MunifTanjim"
#instagram = "MunifTanjim"
linkedin = "wadejohnsontech"
twitter = "hooskers"
#telegram = "MunifTanjim"
#google_scholar = "qc6CJjYAAAAJ"

[params.social.config]
platforms = ["github","twitter","email","linkedin"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

#[[menu.main]]
#name = "Repo"
#weight = -10
#identifier = "repository"
#url = "https://github.com/MunifTanjim/minimo"

#[[menu.main]]
#name = "Posts"
#weight = -11
#identifier = "posts"
#url = "/posts"

[[menu.main]]
name = "Resume"
weight = -13
identifier = "resume"
url = "/resume"

[[menu.main]]
name = "Projects"
weight = -12
identifier = "projects"
url = "/projects"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
