baseURL = "https://hooskers.github.io"
languageCode = "en-us"
title = "Wade"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Wade Johnson"
    description = "Javascript Engineer"
    githubUsername = "hooskers"
    accent = "#673ab7"
    showBorder = true
    backgroundColor = "white"
    font = "Catamaran" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "github"
    highlightLanguages = ["bash", "go", "javascript", "typescript", "css", "json", "html", "protobuf"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:wadej93@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/hooskers/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/hooskers/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/wadejohnsontech/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/story/1215306"
    name = "stack-overflow"
    weight = 5
